export const dynamic = "force-static";

export default function sitemap() {
  const baseUrl = "https://pixconvert.org";
  const lastModified = new Date("2026-06-29T04:28:07.000Z");

  const pages = [
    { path: "", priority: 1.0, freq: "weekly" as const },
    { path: "/avi-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/avif-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/avif-to-bmp", priority: 0.9, freq: "weekly" as const },
    { path: "/avif-to-gif", priority: 0.9, freq: "weekly" as const },
    { path: "/avif-to-ico", priority: 0.9, freq: "weekly" as const },
    { path: "/avif-to-jpeg", priority: 0.9, freq: "weekly" as const },
    { path: "/avif-to-jpg", priority: 0.9, freq: "weekly" as const },
    { path: "/avif-to-png", priority: 0.9, freq: "weekly" as const },
    { path: "/avif-to-tiff", priority: 0.9, freq: "weekly" as const },
    { path: "/avif-to-webp", priority: 0.9, freq: "weekly" as const },
    { path: "/batch-image-converter", priority: 0.8, freq: "weekly" as const },
    { path: "/batch-video-converter", priority: 0.8, freq: "weekly" as const },
    { path: "/bmp-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/bmp-to-avif", priority: 0.9, freq: "weekly" as const },
    { path: "/bmp-to-gif", priority: 0.9, freq: "weekly" as const },
    { path: "/bmp-to-ico", priority: 0.9, freq: "weekly" as const },
    { path: "/bmp-to-jpeg", priority: 0.9, freq: "weekly" as const },
    { path: "/bmp-to-jpg", priority: 0.9, freq: "weekly" as const },
    { path: "/bmp-to-png", priority: 0.9, freq: "weekly" as const },
    { path: "/bmp-to-tiff", priority: 0.9, freq: "weekly" as const },
    { path: "/bmp-to-webp", priority: 0.9, freq: "weekly" as const },
    { path: "/flv-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/gif-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/gif-to-avif", priority: 0.9, freq: "weekly" as const },
    { path: "/gif-to-bmp", priority: 0.9, freq: "weekly" as const },
    { path: "/gif-to-ico", priority: 0.9, freq: "weekly" as const },
    { path: "/gif-to-jpeg", priority: 0.9, freq: "weekly" as const },
    { path: "/gif-to-jpg", priority: 0.9, freq: "weekly" as const },
    { path: "/gif-to-png", priority: 0.9, freq: "weekly" as const },
    { path: "/gif-to-tiff", priority: 0.9, freq: "weekly" as const },
    { path: "/gif-to-webp", priority: 0.9, freq: "weekly" as const },
    { path: "/ico-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/ico-to-avif", priority: 0.9, freq: "weekly" as const },
    { path: "/ico-to-bmp", priority: 0.9, freq: "weekly" as const },
    { path: "/ico-to-gif", priority: 0.9, freq: "weekly" as const },
    { path: "/ico-to-jpeg", priority: 0.9, freq: "weekly" as const },
    { path: "/ico-to-jpg", priority: 0.9, freq: "weekly" as const },
    { path: "/ico-to-png", priority: 0.9, freq: "weekly" as const },
    { path: "/ico-to-tiff", priority: 0.9, freq: "weekly" as const },
    { path: "/ico-to-webp", priority: 0.9, freq: "weekly" as const },
    { path: "/jpeg-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/jpeg-to-avif", priority: 0.9, freq: "weekly" as const },
    { path: "/jpeg-to-bmp", priority: 0.9, freq: "weekly" as const },
    { path: "/jpeg-to-gif", priority: 0.9, freq: "weekly" as const },
    { path: "/jpeg-to-ico", priority: 0.9, freq: "weekly" as const },
    { path: "/jpeg-to-jpg", priority: 0.9, freq: "weekly" as const },
    { path: "/jpeg-to-png", priority: 0.9, freq: "weekly" as const },
    { path: "/jpeg-to-tiff", priority: 0.9, freq: "weekly" as const },
    { path: "/jpeg-to-webp", priority: 0.9, freq: "weekly" as const },
    { path: "/jpg-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/jpg-to-avif", priority: 0.9, freq: "weekly" as const },
    { path: "/jpg-to-bmp", priority: 0.9, freq: "weekly" as const },
    { path: "/jpg-to-gif", priority: 0.9, freq: "weekly" as const },
    { path: "/jpg-to-ico", priority: 0.9, freq: "weekly" as const },
    { path: "/jpg-to-jpeg", priority: 0.9, freq: "weekly" as const },
    { path: "/jpg-to-png", priority: 0.9, freq: "weekly" as const },
    { path: "/jpg-to-tiff", priority: 0.9, freq: "weekly" as const },
    { path: "/jpg-to-webp", priority: 0.9, freq: "weekly" as const },
    { path: "/mkv-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/mov-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/mp4-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/png-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/png-to-avif", priority: 0.9, freq: "weekly" as const },
    { path: "/png-to-bmp", priority: 0.9, freq: "weekly" as const },
    { path: "/png-to-gif", priority: 0.9, freq: "weekly" as const },
    { path: "/png-to-ico", priority: 0.9, freq: "weekly" as const },
    { path: "/png-to-jpeg", priority: 0.9, freq: "weekly" as const },
    { path: "/png-to-jpg", priority: 0.9, freq: "weekly" as const },
    { path: "/png-to-tiff", priority: 0.9, freq: "weekly" as const },
    { path: "/png-to-webp", priority: 0.9, freq: "weekly" as const },
    { path: "/privacy-policy", priority: 0.3, freq: "yearly" as const },
    { path: "/terms-of-service", priority: 0.3, freq: "yearly" as const },
    { path: "/tiff-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/tiff-to-avif", priority: 0.9, freq: "weekly" as const },
    { path: "/tiff-to-bmp", priority: 0.9, freq: "weekly" as const },
    { path: "/tiff-to-gif", priority: 0.9, freq: "weekly" as const },
    { path: "/tiff-to-ico", priority: 0.9, freq: "weekly" as const },
    { path: "/tiff-to-jpeg", priority: 0.9, freq: "weekly" as const },
    { path: "/tiff-to-jpg", priority: 0.9, freq: "weekly" as const },
    { path: "/tiff-to-png", priority: 0.9, freq: "weekly" as const },
    { path: "/tiff-to-webp", priority: 0.9, freq: "weekly" as const },
    { path: "/webp-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/webp-to-avif", priority: 0.9, freq: "weekly" as const },
    { path: "/webp-to-bmp", priority: 0.9, freq: "weekly" as const },
    { path: "/webp-to-gif", priority: 0.9, freq: "weekly" as const },
    { path: "/webp-to-ico", priority: 0.9, freq: "weekly" as const },
    { path: "/webp-to-jpeg", priority: 0.9, freq: "weekly" as const },
    { path: "/webp-to-jpg", priority: 0.9, freq: "weekly" as const },
    { path: "/webp-to-png", priority: 0.9, freq: "weekly" as const },
    { path: "/webp-to-tiff", priority: 0.9, freq: "weekly" as const },
    { path: "/webp-vs-png", priority: 0.7, freq: "monthly" as const },
    { path: "/what-is-webp", priority: 0.7, freq: "monthly" as const },
    { path: "/wmv-converter", priority: 0.85, freq: "weekly" as const },
    { path: "/audio-converter", priority: 0.85, freq: "weekly" as const },
    // PDF Tools
    { path: "/pdf-tools", priority: 0.9, freq: "weekly" as const },
    { path: "/images-to-pdf", priority: 0.9, freq: "weekly" as const },
    { path: "/merge-pdf", priority: 0.9, freq: "weekly" as const },
    { path: "/split-pdf", priority: 0.9, freq: "weekly" as const },
    { path: "/compress-pdf", priority: 0.9, freq: "weekly" as const },
    { path: "/pdf-to-images", priority: 0.9, freq: "weekly" as const },
    { path: "/pdf-watermark", priority: 0.9, freq: "weekly" as const },
    { path: "/protect-pdf", priority: 0.85, freq: "weekly" as const },
    { path: "/rotate-pdf", priority: 0.85, freq: "weekly" as const },
    { path: "/unlock-pdf", priority: 0.85, freq: "weekly" as const },
    { path: "/pdf-page-numbers", priority: 0.85, freq: "weekly" as const },
    { path: "/pdf-add-text", priority: 0.85, freq: "weekly" as const },
    { path: "/crop-pdf", priority: 0.85, freq: "weekly" as const },
  ];

  return pages.map((page) => ({
    url: `${baseUrl}${page.path}`,
    lastModified,
    changeFrequency: page.freq,
    priority: page.priority,
  }));
}
